name: Release

on:
  push:
    tags: ["*"]

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v3
        name: Setup pnpm
        with:
          version: 9

      - name: Setup environment
        run: pnpm install

      - name: Run check for linting errors
        run: pnpm run lint

      - name: Run check for formatting errors
        run: pnpm run format

      - name: Run unit tests
        run: pnpm run test

      - name: Publish package
        run: pnpm -r publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  prebuild-windows:
    name: Prebuild Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        name: Setup Java
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.10"

      - uses: pnpm/action-setup@v3
        name: Setup pnpm
        with:
          version: 8

      - name: Setup Antlr4
        run: pip install --no-input antlr4-tools

      - name: Setup environment
        run: pnpm install

      - name: Prebuild Arch x64
        run: pnpm run prebuild:build:x64

      - name: Prebuild Arch ia32
        run: pnpm run prebuild:build:ia32

      - name: Prebuild upload
        run: pnpm run prebuild:upload
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prebuild-linux:
    name: Prebuild Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup environment
        run: pnpm install

      - name: Prebuild Arch x64
        run: pnpm run prebuild:build:x64

      - name: Prebuild upload
        run: pnpm run prebuild:upload
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
