name: Test

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, reopened]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup environment
        run: pnpm install

      - name: Run check for linting errors
        run: pnpm run lint

      - name: Run check for formatting errors
        run: pnpm run format

      - name: Run build script
        run: pnpm run build

      - name: Run unit tests
        run: pnpm run test
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup environment
        run: pnpm install

      - name: Run check for linting errors
        run: pnpm run lint

      - name: Run check for formatting errors
        run: pnpm run format

      - name: Run build script
        run: pnpm run build

      - name: Run unit tests
        run: pnpm run test
